[package]
name = "api-club-bot"
version = "0.1.5"
edition = "2024"

[dependencies]
log = "0"
pretty_env_logger = "0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
teloxide = { version = "0.15", features = ["macros"] }
version = "3.0.0"
