services:
  bot:
    build:
      context: .
      args:
        BOT_TOKEN: "$BOT_TOKEN"
    environment:
      RUST_LOG: "info"
      BOT_DATA_PATH: "/usr/data"
    volumes:
      - ./data:/usr/data
