services:
  bot:
    build:
      context: .
      secrets:
        - bot_token
    environment:
      RUST_LOG: "info"
      TELOXIDE_TOKEN: "$BOT_TOKEN"

secrets:
  bot_token:
    environment: BOT_TOKEN
