services:
  bot:
    build:
      context: .
      secrets:
        - bot_token
      args:
        BOT_TOKEN: "$BOT_TOKEN"
    environment:
      RUST_LOG: "info"

secrets:
  bot_token:
    environment: BOT_TOKEN
